[[collection]]
type = "card"
title = "KeepOrDelete"
link = "https://github.com/COSC481W-2025Winter/KeepOrDelete"
content = """KeepOrDelete is an interactive and engaging file system management app. Swipe right to keep a file, or swipe left to delete it! Optionally filter and rename files on the fly.

KeepOrDelete is an open-source project developed as my collaborative senior project at Eastern Michigan University. Feel free to file a pull request to suggest a better name.

Visit the [official website](https://cosc481w-2025winter.github.io/KeepOrDelete/) for more information and installation files."""
tags = ["javascript", "electron", "desktop"]

[[collection]]
type = "card"
title = "Condor"
link = "https://github.com/massivebird/condor-web"
content = """Condor is a web dashboard that helps Eastern Michigan University students enroll in courses. The user inputs the IDs of courses that are full, and Condor alerts the user whenever one of these courses become available for enrollment.

I created Condor because one of my required courses didn't have a waitlist. I wrote a simple web scraper to detect if someone dropped the class so I could enroll in their stead. I turned that web scraper into a [library](https://github.com/massivebird/condor), then built a web dashboard around it."""
tags = ["rust", "axum", "web"]

[[collection]]
type = "card"
title = "Arcsearch"
link = "https://github.com/massivebird/arcsearch"
content = """Arcsearch is a bespoke file system querying utility designed for video game archives. It features regular expression support in addition to a suite of customizable behaviors.

Originally written in Bash, maintained in Rust, and partially ported to Python."""
tags = ["rust", "async", "cli", "bash"]

[[collection]]
type = "card"
title = "Lanturn"
link = "https://github.com/massivebird/lanturn"
content = """Lanturn is a utility that regularly reports the connection status of a user-customizable list of  websites. Lanturn is useful for monitoring the status of local network devices and diagnosing network issues.

I wrote Lanturn because my internet goes out sometimes, and I got tired of opening my phone every time I want to check if it's back. Instead, all I need to do is open up Lanturn on my laptop and glance at it once in a while. Anything to make my phone obsolete."""
tags = ["rust", "cli"]

[[collection]]
type = "card"
title = "Voice Assistant (subject to change)"
link = "https://github.com/massivebird/voice-assistant"
content = """This voice assistant program performs real-time voice-to-text recognition to carry out the dutiful will of the user. I wrote this in Python because it has the most accessible voice recognition libraries.

This project was born out of the quintissential need to invoke a voice assistant with the trigger word \"computer\".

_\"Computer, load up Celery Man, please.\"_"""
tags = ["python", "web"]
