# .github/workflows/gh-pages-trigger.yml
name: Trigger on gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:
  post-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public
